### ISSUE TITLE
peer to peer review

### ISSUE THREAD

**Issue by banzaman** [biruk-bereka/Project-2-Portfolio#3]
- Please uncomment your code as it makes the whole codebase unclean.
-  The Pull Request has a proper title and description. ✔️
-  You have added a descriptive README file. Good Job. ✔️
-  There is no linter error present. ✔️
- Please cease using the image tag in HTML
- Try using article tag for the cards.
- Try putting your articles in a section.

**Comment by biruk-bereka** [comment]
The issues are fixed.
